/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.MedicHistoryGUI;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import project.database.DatabaseConnection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.*;
/**
 *
 * @author harshit_nagpal
 */
public class DoctorPanelUI extends javax.swing.JFrame {

    private String doctorID;
    private String hospitalID;
    private String name;
    private String spec;
    private String email;
    private String selectedHospital;
    private String hospital;

//    private String bloodType;
    /**
     * Creates new form DoctorPanelUI
     */
    public DoctorPanelUI(String doctorID) {
        initComponents();
        this.doctorID =doctorID ;
        try (Connection connection = DatabaseConnection.getConnection()) {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery(
                    "SELECT name, specialization ,email FROM Doctor WHERE doctorID = '" + doctorID + "'");

            if (rs.next()) {
            this.name = rs.getString("name");
            this.email=rs.getString("email");
            this.spec=rs.getString("specialization");
            System.out.println(this.name);
            docname.setText(this.name);
//            BloodTypeField.setText(rs.getString("blood_type"));
//            weightField.setText(rs.getString("weight"));
//            heightField.setText(rs.getString("height"));
            welcomeDoctorName.setText(this.name+"👋");
            userId.setText(this.email);
            specialisation.setText(this.spec);
            }
            edit.setVisible(false);
        } catch (SQLException ex) {
        }
        try (Connection conn = DatabaseConnection.getConnection()) {
            Statement stmt = conn.createStatement();

            String query = "SELECT h.name " +
                           "FROM HOSPITAL h " +
                           "INNER JOIN WORKS w ON h.hospitalID = w.hospitalID " +
                           "WHERE w.doctorID = '" + doctorID + "'";

            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                hospital = rs.getString("name");
                hospitalname.setText(hospital);
                System.out.println("Doctor with ID " + doctorID + " works at " + hospital + " hospital.");
            } else {
                System.out.println("Doctor with ID " + doctorID + " not found or not assigned to any hospital.");
            }

            rs.close();
        }
        catch(Exception e)
        {

        }
        
                try (Connection connection = DatabaseConnection.getConnection()) {
            Statement stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT name FROM Hospital");
            while (rs.next()) {
                HospitalDropDown.addItem(rs.getString("name"));
            }
                HospitalDropDown.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        selectedHospital = (String) e.getItem();
                        System.out.println(selectedHospital);
//                        populateDoctorComboBox(doctorComboBox, selectedHospital);
                    }
                }
            });

            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.edit
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        welcomeDoctorName = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        closepopup = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        positiontext = new javax.swing.JTextField();
        HospitalDropDown = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        specialisation = new javax.swing.JLabel();
        hospitalname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editinfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        docname = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        patientlist = new javax.swing.JButton();
        medreq = new javax.swing.JButton();
        newpres = new javax.swing.JButton();
        newpres1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem1.setText("jMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Welcome,");

        welcomeDoctorName.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        welcomeDoctorName.setText("PatientName");

        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                editPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel4.setText("Edit Personal Info");

        jLabel18.setText("Position");

        jLabel20.setText("Hospital");

        closepopup.setBackground(new java.awt.Color(255, 51, 51));
        closepopup.setForeground(new java.awt.Color(242, 242, 242));
        closepopup.setText("Close");
        closepopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closepopupActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(102, 102, 255));
        submit.setForeground(new java.awt.Color(242, 242, 242));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        positiontext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positiontextActionPerformed(evt);
            }
        });

        HospitalDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalDropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HospitalDropDown, 0, 236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit)
                            .addComponent(closepopup)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(positiontext)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positiontext, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HospitalDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closepopup)
                .addGap(16, 16, 16))
        );

        jLabel14.setText("User Id:-");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("BASIC INFO ");

        userId.setText("ABCD");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        specialisation.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        specialisation.setForeground(new java.awt.Color(242, 242, 242));
        specialisation.setText("DOCTOR");

        hospitalname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        hospitalname.setForeground(new java.awt.Color(242, 242, 242));
        hospitalname.setText("Hospital Name");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/MedicHistoryGUI/WhatsApp Image 2024-04-08 at 23.22.15_a1b4f370.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        editinfo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        editinfo.setText("Edit Info");
        editinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialisation, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editinfo)
                    .addComponent(hospitalname, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(specialisation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editinfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel9.setText("Medic History");

        docname.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        docname.setText("DoctorName");

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        patientlist.setBackground(new java.awt.Color(102, 102, 255));
        patientlist.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        patientlist.setForeground(new java.awt.Color(255, 255, 255));
        patientlist.setText("Appointment List");
        patientlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientlistActionPerformed(evt);
            }
        });

        medreq.setBackground(new java.awt.Color(102, 102, 255));
        medreq.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        medreq.setForeground(new java.awt.Color(255, 255, 255));
        medreq.setText("Med Request");
        medreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medreqActionPerformed(evt);
            }
        });

        newpres.setBackground(new java.awt.Color(102, 102, 255));
        newpres.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        newpres.setForeground(new java.awt.Color(255, 255, 255));
        newpres.setText("Create New Prescription");
        newpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpresActionPerformed(evt);
            }
        });

        newpres1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        newpres1.setForeground(new java.awt.Color(102, 102, 255));
        newpres1.setText("SignOut");
        newpres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpres1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medreq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newpres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(docname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newpres1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(68, 68, 68)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(medreq, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientlist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newpres, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(docname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newpres1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(351, 351, 351))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeDoctorName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userId))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(welcomeDoctorName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(userId))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    edit.setVisible(false);
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void patientlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientlistActionPerformed
        // TODO add your handling code here:
        System.out.println("hello");
        
        try {
            doctorpatientlistui(doctorID);
        } catch (SQLException ex) {
            Logger.getLogger(DoctorPanelUI.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_patientlistActionPerformed

    private void medreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medreqActionPerformed
        // TODO add your handling code here:
        try{
            MedRequest medreq=new MedRequest(doctorID,name,email);
                    medreq.setVisible(true);
        this.dispose();
        }
        catch(Exception e)
        {
        }

        
    }//GEN-LAST:event_medreqActionPerformed

    private void newpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpresActionPerformed
        // TODO add your handling code here:
        DoctorRecieptUI docrec=new DoctorRecieptUI(doctorID,name,email);
        docrec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newpresActionPerformed

    private void editinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editinfoActionPerformed
                // TODO add your handling code here:
//   edit.se
//                e
            edit.setVisible(true);
    }//GEN-LAST:event_editinfoActionPerformed

    private void editPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_editPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_editPropertyChange

    private void closepopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closepopupActionPerformed
            edit.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_closepopupActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:'
        editdetails();

    }//GEN-LAST:event_submitActionPerformed
    private void editdetails()
    {
        
        String posn=positiontext.getText();
        try(Connection conn= DatabaseConnection.getConnection()) {
           Statement stmt=conn.createStatement();
        String updateDoctorQuery = "UPDATE DOCTOR SET specialization = '" + posn + "' WHERE doctorID = ?";
            PreparedStatement updateDoctorStmt = conn.prepareStatement(updateDoctorQuery);
            updateDoctorStmt.setString(1, doctorID); // You need to provide the doctor_id here
            updateDoctorStmt.executeUpdate();

            // Update doctor's hospital
            String updateHospitalQuery = "UPDATE WORKS SET hospitalID = (SELECT hospitalID FROM HOSPITAL WHERE name = ?) WHERE doctorID = ?";
            PreparedStatement updateHospitalStmt = conn.prepareStatement(updateHospitalQuery);
            updateHospitalStmt.setString(1, selectedHospital);
            updateHospitalStmt.setString(2, doctorID); // You need to provide the doctor_id here
            updateHospitalStmt.executeUpdate();

            System.out.println("Doctor's specialization and hospital updated successfully.");
//            selectedHospital
            specialisation.setText(posn);
            hospitalname.setText(selectedHospital);
            JOptionPane.showMessageDialog(null, "Details updated succesfuly");
        } catch (SQLException se) {
            se.printStackTrace();
        }
//        String hos=hospitaltext.getText();
//        
//        try (Connection conn = DatabaseConnection.getConnection()) {
//            // Update specialization in DOCTOR table
//            String updateSpecializationQuery = "UPDATE DOCTOR SET specialization = ? WHERE doctor_id = ?";
//            updateDoctor(conn, updateSpecializationQuery, posn);
//
//            // Update hospital in WORKS table
//            String updateHospitalQuery = "UPDATE WORKS SET hospital_id = (SELECT hospital_id FROM HOSPITAL WHERE name = ?) WHERE doctor_id = ?";
//            updateHospital(conn, updateHospitalQuery, hos);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
    }
//     private static void updateDoctor(Connection conn, String query, String specialization) throws SQLException {
//        try (PreparedStatement stmt = conn.prepareStatement(query)) {
//            stmt.setString(1, specialization);
//            stmt.setInt(2, getDoctorId(conn));
//            int rowsUpdated = stmt.executeUpdate();
//            System.out.println(rowsUpdated + " row(s) updated in DOCTOR table.");
//        }
//    }
//
//    private static void updateHospital(Connection conn, String query, String hospital) throws SQLException {
//        try (PreparedStatement stmt = conn.prepareStatement(query)) {
//            stmt.setString(1, hospital);
//            stmt.setInt(2, getDoctorId(conn));
//            int rowsUpdated = stmt.executeUpdate();
//            System.out.println(rowsUpdated + " row(s) updated in WORKS table.");
//        }
//    }
//    
    private void positiontextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positiontextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positiontextActionPerformed

    private void HospitalDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HospitalDropDownActionPerformed

    private void newpres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpres1ActionPerformed
        LoginUI login = new LoginUI();
       
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_newpres1ActionPerformed
private void doctorpatientlistui(String doctorID) throws SQLException {
        // Create an instance of the patient panel GUI
        Docpatientlist patientlistPanel = new Docpatientlist(doctorID,name,email);

        // Show the patient panel GUI
        System.out.println(doctorID);
        patientlistPanel.setVisible(true);
System.out.println("hello3");
        // Dispose or hide the login GUI
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//
//        try {
//              javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(DoctorPanelUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoctorPanelUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HospitalDropDown;
    private javax.swing.JButton closepopup;
    private javax.swing.JLabel docname;
    private javax.swing.JPanel edit;
    private javax.swing.JButton editinfo;
    private javax.swing.JLabel hospitalname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton medreq;
    private javax.swing.JButton newpres;
    private javax.swing.JButton newpres1;
    private javax.swing.JButton patientlist;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField positiontext;
    private javax.swing.JLabel specialisation;
    private javax.swing.JButton submit;
    private javax.swing.JLabel userId;
    private javax.swing.JLabel welcomeDoctorName;
    // End of variables declaration//GEN-END:variables
}
