/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.MedicHistoryGUI;

/**
 *
 * @author harshit_nagpal
 */
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.sql.Connection;
import project.database.DatabaseConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

public class LoginUII extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUII() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        passwordField = new javax.swing.JPasswordField();
        LoginPatient = new javax.swing.JButton();
        LoginDoctor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordField.setText("qwerty");

        LoginPatient.setText("Sign in as Patient");
        LoginPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPatientActionPerformed(evt);
            }
        });
        

        LoginDoctor.setText("Sign in as Doctor");
        LoginDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginDoctorActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel3.setText("Email");

        usernameField.setText("jane.smith@example.com");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginDoctor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordField)
                    .addComponent(usernameField)
                    .addComponent(LoginPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPatient)
                    .addComponent(LoginDoctor))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void LoginDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginDoctorActionPerformed
        // TODO add your handling code here:
                String email = usernameField.getText();
        String password = new String(passwordField.getPassword());
        

        try (Connection connection = DatabaseConnection.getConnection()) {
            String query = "SELECT * FROM Doctor WHERE email = ? AND password = ?";
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, email);
            pstmt.setString(2, password);
            ResultSet rs = pstmt.executeQuery();
            

            if (rs.next()) {
                String userID = rs.getString("name");
                showDoctorPanel(rs.getString("doctorID"));
                System.out.println(userID);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            pstmt.close();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_LoginDoctorActionPerformed

    private void showDoctorPanel(String doctorID) {
        // Create an instance of the patient panel GUI
        DoctorPanelUI doctorPanel = new DoctorPanelUI(doctorID);

        // Show the patient panel GUI
        doctorPanel.setVisible(true);

        // Dispose or hide the login GUI
        this.dispose(); // or this.setVisible(false);
    }

private void showPatientPanel(String patientID) {
        // Create an instance of the patient panel GUI
        PatientPanelUI patientPanel = new PatientPanelUI(patientID);

        // Show the patient panel GUI
        patientPanel.setVisible(true);

        // Dispose or hide the login GUI
        this.dispose(); // or this.setVisible(false);
}
    private void LoginPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPatientActionPerformed
String email = usernameField.getText();
        String password = new String(passwordField.getPassword());
        

        try (Connection connection = DatabaseConnection.getConnection()) {
            String query = "SELECT * FROM Patient WHERE email = ? AND password = ?";
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, email);
            pstmt.setString(2, password);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String userID = rs.getString("name");
                showPatientPanel(rs.getString("patientID"));
//                System.out.println(userID);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            pstmt.close();
        } catch(SQLException ex) {
        }

    }//GEN-LAST:event_LoginPatientActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        try {
//            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(PatientPanelUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginUII().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginDoctor;
    private javax.swing.JButton LoginPatient;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
